# Generated by export_gap.py -- do not edit.
# Transformation systems of the DN/WTA finite-state audit.
# One-based GAP indexing: exported entry = zero-based image + 1.

### DN3: degree 3, 3 generators (D0, D1, D2)
deg_DN3 := 3;;
gennames_DN3 := [ "D0", "D1", "D2" ];;
genlists_DN3 := [
  [ 1, 1, 1 ],   # D0
  [ 3, 2, 1 ],   # D1
  [ 3, 3, 2 ]   # D2
];;
gens_DN3 := List(genlists_DN3, l -> TransformationNC(l));;

### DN4: degree 4, 4 generators (D0, D1, D2, D3)
deg_DN4 := 4;;
gennames_DN4 := [ "D0", "D1", "D2", "D3" ];;
genlists_DN4 := [
  [ 1, 1, 1, 1 ],   # D0
  [ 2, 2, 1, 1 ],   # D1
  [ 3, 2, 2, 2 ],   # D2
  [ 4, 3, 3, 2 ]   # D3
];;
gens_DN4 := List(genlists_DN4, l -> TransformationNC(l));;

### WTA: degree 8, 4 generators (W00, W10, W01, W11)
deg_WTA := 8;;
gennames_WTA := [ "W00", "W10", "W01", "W11" ];;
genlists_WTA := [
  [ 1, 1, 4, 2, 6, 2, 2, 2 ],   # W00
  [ 5, 5, 8, 2, 6, 6, 6, 6 ],   # W10
  [ 3, 3, 4, 4, 8, 2, 4, 4 ],   # W01
  [ 7, 7, 8, 4, 8, 6, 8, 8 ]   # W11
];;
gens_WTA := List(genlists_WTA, l -> TransformationNC(l));;

### prod: degree 32, 4 generators (g0, g1, g2, g3)
deg_prod := 32;;
gennames_prod := [ "g0", "g1", "g2", "g3" ];;
genlists_prod := [
  [ 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2 ],   # g0
  [ 13, 13, 16, 10, 14, 14, 14, 14, 13, 13, 16, 10, 14, 14, 14, 14, 5, 5, 8, 2, 6, 6, 6, 6, 5, 5, 8, 2, 6, 6, 6, 6 ],   # g1
  [ 19, 19, 20, 20, 24, 18, 20, 20, 11, 11, 12, 12, 16, 10, 12, 12, 11, 11, 12, 12, 16, 10, 12, 12, 11, 11, 12, 12, 16, 10, 12, 12 ],   # g2
  [ 31, 31, 32, 28, 32, 30, 32, 32, 23, 23, 24, 20, 24, 22, 24, 24, 23, 23, 24, 20, 24, 22, 24, 24, 15, 15, 16, 12, 16, 14, 16, 16 ]   # g3
];;
gens_prod := List(genlists_prod, l -> TransformationNC(l));;

### D_to_W: degree 32, 4 generators (g0, g1, g2, g3)
deg_D_to_W := 32;;
gennames_D_to_W := [ "g0", "g1", "g2", "g3" ];;
genlists_D_to_W := [
  [ 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2 ],   # g0
  [ 13, 13, 16, 10, 14, 14, 14, 14, 13, 13, 16, 10, 14, 14, 14, 14, 1, 1, 4, 2, 6, 2, 2, 2, 1, 1, 4, 2, 6, 2, 2, 2 ],   # g1
  [ 19, 19, 20, 20, 24, 18, 20, 20, 13, 13, 16, 10, 14, 14, 14, 14, 13, 13, 16, 10, 14, 14, 14, 14, 13, 13, 16, 10, 14, 14, 14, 14 ],   # g2
  [ 31, 31, 32, 28, 32, 30, 32, 32, 19, 19, 20, 20, 24, 18, 20, 20, 19, 19, 20, 20, 24, 18, 20, 20, 13, 13, 16, 10, 14, 14, 14, 14 ]   # g3
];;
gens_D_to_W := List(genlists_D_to_W, l -> TransformationNC(l));;

### W_to_D: degree 32, 4 generators (g0, g1, g2, g3)
deg_W_to_D := 32;;
gennames_W_to_D := [ "g0", "g1", "g2", "g3" ];;
genlists_W_to_D := [
  [ 1, 1, 28, 26, 30, 26, 26, 26, 1, 1, 20, 18, 22, 18, 18, 18, 1, 1, 20, 18, 22, 18, 18, 18, 1, 1, 12, 10, 14, 10, 10, 10 ],   # g0
  [ 13, 13, 32, 26, 30, 30, 30, 30, 13, 13, 24, 18, 22, 22, 22, 22, 5, 5, 24, 18, 22, 22, 22, 22, 5, 5, 16, 10, 14, 14, 14, 14 ],   # g1
  [ 19, 19, 28, 28, 32, 26, 28, 28, 11, 11, 20, 20, 24, 18, 20, 20, 11, 11, 20, 20, 24, 18, 20, 20, 11, 11, 12, 12, 16, 10, 12, 12 ],   # g2
  [ 31, 31, 32, 28, 32, 30, 32, 32, 23, 23, 24, 20, 24, 22, 24, 24, 23, 23, 24, 20, 24, 22, 24, 24, 15, 15, 16, 12, 16, 14, 16, 16 ]   # g3
];;
gens_W_to_D := List(genlists_W_to_D, l -> TransformationNC(l));;

### rec_sync: degree 32, 4 generators (g0, g1, g2, g3)
deg_rec_sync := 32;;
gennames_rec_sync := [ "g0", "g1", "g2", "g3" ];;
genlists_rec_sync := [
  [ 1, 25, 20, 26, 14, 26, 26, 26, 5, 21, 16, 18, 14, 22, 22, 22, 3, 19, 12, 20, 8, 18, 20, 20, 7, 15, 16, 12, 8, 14, 16, 16 ],   # g0
  [ 1, 25, 20, 26, 14, 26, 26, 26, 5, 21, 16, 18, 14, 22, 22, 22, 3, 19, 12, 20, 8, 18, 20, 20, 7, 15, 16, 12, 8, 14, 16, 16 ],   # g1
  [ 1, 25, 20, 26, 14, 26, 26, 26, 5, 21, 16, 18, 14, 22, 22, 22, 3, 19, 12, 20, 8, 18, 20, 20, 7, 15, 16, 12, 8, 14, 16, 16 ],   # g2
  [ 1, 25, 20, 26, 14, 26, 26, 26, 5, 21, 16, 18, 14, 22, 22, 22, 3, 19, 12, 20, 8, 18, 20, 20, 7, 15, 16, 12, 8, 14, 16, 16 ]   # g3
];;
gens_rec_sync := List(genlists_rec_sync, l -> TransformationNC(l));;

### rec_async_D: degree 32, 4 generators (g0, g1, g2, g3)
deg_rec_async_D := 32;;
gennames_rec_async_D := [ "g0", "g1", "g2", "g3" ];;
genlists_rec_async_D := [
  [ 1, 31, 20, 28, 14, 30, 32, 32, 1, 19, 16, 20, 14, 18, 20, 20, 1, 19, 16, 20, 6, 18, 20, 20, 1, 13, 16, 10, 6, 14, 14, 14 ],   # g0
  [ 1, 31, 20, 28, 14, 30, 32, 32, 1, 19, 16, 20, 14, 18, 20, 20, 1, 19, 16, 20, 6, 18, 20, 20, 1, 13, 16, 10, 6, 14, 14, 14 ],   # g1
  [ 1, 31, 20, 28, 14, 30, 32, 32, 1, 19, 16, 20, 14, 18, 20, 20, 1, 19, 16, 20, 6, 18, 20, 20, 1, 13, 16, 10, 6, 14, 14, 14 ],   # g2
  [ 1, 31, 20, 28, 14, 30, 32, 32, 1, 19, 16, 20, 14, 18, 20, 20, 1, 19, 16, 20, 6, 18, 20, 20, 1, 13, 16, 10, 6, 14, 14, 14 ]   # g3
];;
gens_rec_async_D := List(genlists_rec_async_D, l -> TransformationNC(l));;

### rec_async_W: degree 32, 4 generators (g0, g1, g2, g3)
deg_rec_async_W := 32;;
gennames_rec_async_W := [ "g0", "g1", "g2", "g3" ];;
genlists_rec_async_W := [
  [ 1, 1, 28, 26, 30, 26, 26, 26, 13, 13, 24, 18, 22, 22, 22, 22, 11, 11, 20, 20, 24, 18, 20, 20, 15, 15, 16, 12, 16, 14, 16, 16 ],   # g0
  [ 1, 1, 28, 26, 30, 26, 26, 26, 13, 13, 24, 18, 22, 22, 22, 22, 11, 11, 20, 20, 24, 18, 20, 20, 15, 15, 16, 12, 16, 14, 16, 16 ],   # g1
  [ 1, 1, 28, 26, 30, 26, 26, 26, 13, 13, 24, 18, 22, 22, 22, 22, 11, 11, 20, 20, 24, 18, 20, 20, 15, 15, 16, 12, 16, 14, 16, 16 ],   # g2
  [ 1, 1, 28, 26, 30, 26, 26, 26, 13, 13, 24, 18, 22, 22, 22, 22, 11, 11, 20, 20, 24, 18, 20, 20, 15, 15, 16, 12, 16, 14, 16, 16 ]   # g3
];;
gens_rec_async_W := List(genlists_rec_async_W, l -> TransformationNC(l));;

SYSTEMS := [
  rec( name := "DN3", deg := deg_DN3, gens := gens_DN3, gennames := gennames_DN3 ),
  rec( name := "DN4", deg := deg_DN4, gens := gens_DN4, gennames := gennames_DN4 ),
  rec( name := "WTA", deg := deg_WTA, gens := gens_WTA, gennames := gennames_WTA ),
  rec( name := "prod", deg := deg_prod, gens := gens_prod, gennames := gennames_prod ),
  rec( name := "D_to_W", deg := deg_D_to_W, gens := gens_D_to_W, gennames := gennames_D_to_W ),
  rec( name := "W_to_D", deg := deg_W_to_D, gens := gens_W_to_D, gennames := gennames_W_to_D ),
  rec( name := "rec_sync", deg := deg_rec_sync, gens := gens_rec_sync, gennames := gennames_rec_sync ),
  rec( name := "rec_async_D", deg := deg_rec_async_D, gens := gens_rec_async_D, gennames := gennames_rec_async_D ),
  rec( name := "rec_async_W", deg := deg_rec_async_W, gens := gens_rec_async_W, gennames := gennames_rec_async_W )
];;
