##############################################################################
##  transcript.g -- generates gap_transcript.txt, the supplementary GAP
##  session for the manuscript.  Every command is echoed in "gap> " form
##  followed by its actual output, so the file reads as a reproducible
##  session rather than a report.
##
##  Run:  gap -q -A -o 8g transcript.g
##############################################################################

LoadPackage("sgpdec", false);;
SgpDecOptionsRec.SMALL_GROUPS := true;;
Read("gap_systems.g");

T := OutputTextFile("gap_transcript.txt", false);;
SetPrintFormattingStatus(T, false);;

W := function(arg)
  local s;
  for s in arg do AppendTo(T, s); od;
end;;
Hdr := function(s)
  W("\n");
  W("################################################################################\n");
  W("## ", s, "\n");
  W("################################################################################\n");
end;;
##  echo a command and its value
Cmd := function(cmdstr, val)
  W("gap> ", cmdstr, "\n", String(val), "\n");
end;;

W("################################################################################\n");
W("## SUPPLEMENTARY GAP TRANSCRIPT\n");
W("## Krohn-Rhodes / holonomy structure of canonical DN and WTA neural motifs\n");
W("##\n");
W("## Software:  GAP 4.15.1;  packages: sgpdec 1.2.0, semigroups 5.6.3,\n");
W("##            digraphs 1.15.0, orb 5.1.0, images 1.4.0, datastructures 0.4.3\n");
W("##\n");
W("## Reproduce with:\n");
W("##     gap -q -A -o 8g transcript.g\n");
W("## after placing gap_systems.g (generated by export_gap.py) in the same\n");
W("## directory.  gap_systems.g defines, for each system NAME, the variables\n");
W("## deg_NAME, gens_NAME and gennames_NAME, plus the list SYSTEMS.\n");
W("##\n");
W("## CONVENTIONS\n");
W("##   GAP is ONE-BASED: GAP point p corresponds to paper state p-1.\n");
W("##   A transformation on X={0..n-1} is written as the tuple (f(0),...,f(n-1))\n");
W("##   in the paper and as its one-based image list in GAP.\n");
W("##   DN 4-state:  X_D = {0,1,2,3}.\n");
W("##   WTA:         X_W = {0,1}^3 encoded q = 4*b1 + 2*b2 + g.\n");
W("##   Composite:   32 states, idx(d,w) = 8*d + w.\n");
W("##\n");
W("## A note on what a HOLONOMY GROUP acts on, which matters for how these\n");
W("## numbers may be quoted.  For an image set C of the skeleton:\n");
W("##   * PermutatorGroup(sk, C) is the group of permutations of the RAW STATES\n");
W("##     of C induced by words that map C onto itself.\n");
W("##   * The holonomy group is the image of that group acting on the TILES of\n");
W("##     C (the maximal proper subsets of C that are themselves image sets).\n");
W("##   These differ in general.  When every tile is a singleton the two\n");
W("##   coincide and the group genuinely permutes states; when the tiles are\n");
W("##   larger, the group permutes SUBSETS and no claim about individual states\n");
W("##   is licensed.  Both are reported below.\n");
W("################################################################################\n");

W("\ngap> LoadPackage(\"sgpdec\", false);;\n");
W("gap> SgpDecOptionsRec.SMALL_GROUPS := true;;\n");
W("gap> Read(\"gap_systems.g\");\n");

##  systems in paper order
ORDER := ["DN3","DN4","WTA","prod","D_to_W","W_to_D",
          "rec_sync","rec_async_D","rec_async_W"];;
##  cascade faithfulness is run only where it is computationally feasible
CASCOK := ["DN3","DN4","WTA","prod","rec_sync","rec_async_D","rec_async_W"];;

Fmt := function(x, deg)
  local b;
  if deg = 8 then
    b := [QuoInt(x,4), QuoInt(x,2) mod 2, x mod 2];
    return Concatenation(String(x),"=(",String(b[1]),",",String(b[2]),",",String(b[3]),")");
  elif deg = 32 then
    return Concatenation(String(x),"=(D:",String(QuoInt(x,8)),",W:",String(x mod 8),")");
  fi;
  return String(x);
end;;
Show := function(bl, deg)
  return Concatenation("{", JoinStringsWithSeparator(
    List(ListBlist([1..deg], bl), p -> Fmt(p-1, deg)), " "), "}");
end;;

for nm in ORDER do
  sysrec := First(SYSTEMS, s -> s.name = nm);;
  deg := sysrec.deg;; gens := sysrec.gens;;
  Hdr(Concatenation("SYSTEM ", nm, "   (degree ", String(deg), ")"));

  W("gap> gens_", nm, ";\n");
  W(String(gens), "\n");
  W("##   generator names: ", JoinStringsWithSeparator(sysrec.gennames, ", "), "\n");

  W("\n## ---- transition monoid ----\n");
  M := Monoid(gens);; S := Semigroup(gens);;
  Cmd(Concatenation("M := Monoid(gens_", nm, ");; Size(M);"), Size(M));
  W("##   (Semigroup(gens) omits the identity unless it is a product of\n");
  W("##    generators; Size(Semigroup(gens)) = ");
  W(String(Size(S)), " here, so the paper's |M| is the Monoid value.)\n");
  Cmd("IsAperiodicSemigroup(M);", IsAperiodicSemigroup(M));
  Cmd("Length(Idempotents(M));", Length(Idempotents(M)));
  nonap := Number(AsList(M), t -> t^deg <> t^(deg+1));;
  W("gap> Number(AsList(M), t -> t^", deg, " <> t^", deg+1, ");   ## non-aperiodic elements\n");
  W(String(nonap), "\n");
  U := GroupOfUnits(M);;
  Cmd("Size(GroupOfUnits(M));", Size(U));
  Cmd("StructureDescription(Range(IsomorphismPermGroup(GroupOfUnits(M))));",
      StructureDescription(Range(IsomorphismPermGroup(U))));

  W("\n## ---- aperiodicity of each generator ----\n");
  W("##   t is aperiodic iff t^n = t^(n+1) (n = degree): every cycle of the\n");
  W("##   functional graph is a fixed point.\n");
  for i in [1..Length(gens)] do
    W("gap> t := gens_", nm, "[", i, ");; t^", deg, " = t^", deg+1, ";   ## ",
      sysrec.gennames[i], "\n");
    W(String(gens[i]^deg = gens[i]^(deg+1)), "\n");
  od;

  W("\n## ---- holonomy skeleton ----\n");
  sk := Skeleton(M);;
  Cmd("sk := Skeleton(M);; DepthOfSkeleton(sk);", DepthOfSkeleton(sk));
  W("gap> DisplayHolonomyComponents(sk);\n");
  W(DisplayStringHolonomyComponents(sk));
  W("##   Reading: \"level: n\" is a trivial component on n tiles;\n");
  W("##   \"(n,G)\" is a component of n tiles carrying group G.\n");

  W("\n## ---- group components, with supports decoded ----\n");
  W("gap> gc := GroupComponents(sk);; rs := RepresentativeSets(sk);;\n");
  gc := GroupComponents(sk);; rs := RepresentativeSets(sk);;
  ntc := 0;;
  for d in [1..Length(gc)] do
    for i in [1..Length(gc[d])] do
      G := gc[d][i];;
      if IsTrivial(G) then continue; fi;
      ntc := ntc + 1;
      W("##   level ", d, " slot ", i, ": ", String(G), "  |G| = ", Size(G),
        "  ", StructureDescription(G), "\n");
      W("##       representative set : ", Show(rs[d][i], deg), "\n");
      W("##       tiles permuted     : ",
        JoinStringsWithSeparator(List(TilesOf(sk, rs[d][i]),
                                      t -> Show(t, deg)), " | "), "\n");
    od;
  od;
  if ntc = 0 then
    W("##   ALL group components are trivial: the monoid is APERIODIC and its\n");
    W("##   Krohn-Rhodes decomposition needs no nontrivial group.\n");
  fi;

  if nm in CASCOK then
    W("\n## ---- faithfulness of the holonomy decomposition ----\n");
    hcs := HolonomyCascadeSemigroup(M);;
    hom := HomomorphismTransformationSemigroup(hcs);;
    R := Range(hom);;
    W("gap> hcs := HolonomyCascadeSemigroup(M);;\n");
    W("gap> hom := HomomorphismTransformationSemigroup(hcs);;\n");
    Cmd("Size(Range(hom));", Size(R));
    Cmd("AsSortedList(M) = AsSortedList(Range(hom));",
        AsSortedList(M) = AsSortedList(R));
    if AsSortedList(M) <> AsSortedList(R) then
      W("##   The set difference is exactly:\n");
      W("##   ", String(Difference(AsSortedList(M), AsSortedList(R))), "\n");
      W("##   i.e. only the identity, because Range(hom) is built with\n");
      W("##   Semigroup(...) from the cascade generators.  This is a\n");
      W("##   Semigroup-vs-Monoid bookkeeping artefact, NOT a failure of the\n");
      W("##   decomposition.  The elementwise test below is the real check.\n");
    fi;
    W("gap> ForAll(AsList(M), t -> AsHolonomyTransformation(AsHolonomyCascade(t, sk), sk) = t);\n");
    W(String(ForAll(AsList(M),
        t -> AsHolonomyTransformation(AsHolonomyCascade(t, sk), sk) = t)), "\n");
    W("##   TRUE means every element of M is recovered exactly from its\n");
    W("##   cascade coordinates: the decomposition is faithful.\n");
  else
    W("\n## ---- faithfulness of the holonomy decomposition ----\n");
    W("##   NOT ATTEMPTED for this system.  The holonomy cascade has\n");
    cv := List(CoordVals(sk), Size);;
    W("##   coordinate-value counts ", String(cv), ",\n");
    W("##   i.e. a cascade state space of ", String(Product(cv)), " tuples;\n");
    W("##   constructing a single cascade element exhausts memory at -o 14g.\n");
    W("##   The skeleton, its depth, and all group components above are exact;\n");
    W("##   only the explicit cascade reconstruction is omitted.\n");
  fi;
od;

##############################################################################
Hdr("TARGETED CHECKS OF THE CLAIMS MADE IN THE TEXT");

W("## For a state subset C we report:\n");
W("##   PermutatorGroup(sk, C)  -- action on the RAW STATES of C\n");
W("##   holonomy group          -- induced action on the TILES of C\n");
W("##   the subduction class of C and that class's transversal representative\n");
W("##     (holonomy groups are conjugate, hence isomorphic, along a class, so a\n");
W("##      set that is not the chosen representative still carries the group of\n");
W("##      its class -- it simply does not appear in GroupComponents output)\n");

Check := function(nm, states, note)
  local sysrec, deg, M, sk, C, P, H, cls, RS, d, i, tiles;
  sysrec := First(SYSTEMS, s -> s.name = nm);
  deg := sysrec.deg;
  M := Monoid(sysrec.gens); sk := Skeleton(M);
  C := FiniteSet(List(states, x -> x + 1), deg);
  W("\n## ", note, "\n");
  W("gap> C := FiniteSet(", String(List(states, x -> x+1)), ", ", deg,
    ");;   ## paper states ", String(states), " = ", Show(C, deg), "\n");
  if not (C in ForwardOrbit(sk)) then
    W("##   C is NOT an image set of this skeleton -- no holonomy group is\n");
    W("##   attached to it, and no claim about it can be made.\n");
    return;
  fi;
  P := PermutatorGroup(sk, C);
  H := Image(PermutatorHolonomyHomomorphism(sk, C));
  tiles := TilesOf(sk, C);
  Cmd("DepthOfSet(sk, C);", DepthOfSet(sk, C));
  Cmd("PermutatorGroup(sk, C);", P);
  W("##   ", StructureDescription(P), " on the raw states\n");
  W("gap> Image(PermutatorHolonomyHomomorphism(sk, C));\n");
  W(String(H), "\n");
  W("##   ", StructureDescription(H), " on the ", Length(tiles), " tiles: ",
    JoinStringsWithSeparator(List(tiles, t -> Show(t, deg)), " | "), "\n");
  if ForAll(tiles, t -> SizeBlist(t) = 1) then
    W("##   All tiles are SINGLETONS, so this group permutes individual states.\n");
  else
    W("##   Tiles are NOT singletons: the group permutes SUBSETS, and the\n");
    W("##   paper must not describe it as permuting the individual states.\n");
  fi;
  cls := SubductionClassOfSet(sk, C);
  RS := RepresentativeSets(sk);
  W("gap> Length(SubductionClassOfSet(sk, C));\n", String(Length(cls)), "\n");
  for d in [1..Length(RS)] do
    for i in [1..Length(RS[d])] do
      if RS[d][i] in cls then
        W("##   class representative = level ", d, " slot ", i, " = ",
          Show(RS[d][i], deg), "\n");
      fi;
    od;
  od;
end;;

Check("DN4", [1,2],
      "(b) DN4: does the level-3 C2 correspond to the audit witness cycle 2<->1?");
Check("DN4", [0,1],
      "    DN4: the transversal representative of that same class.");
Check("WTA", [4,5],
      "(a) WTA: is there a C2 supported on {4,5} (GAP {5,6})?");
Check("WTA", [2,3],
      "(a) WTA: and on the symmetric counterpart {2,3} (GAP {3,4})?");
Check("W_to_D", [4,13],
      "(c) W_to_D KEY CLAIM: a nontrivial group whose support contains BOTH composite state 4 = (D:0,W:4) and 13 = (D:1,W:5) (GAP points 5 and 14).");
Check("prod", [12,13],
      "(d) prod: the corresponding pair 12,13 in the product control.");
Check("D_to_W", [12,13],
      "(e) D_to_W: the corresponding pair 12,13.");

Hdr("IS THE GROUP ACTION INHERITED FROM A FACTOR, OR GENUINELY COMPOSITE?");
W("## A permutation of composite states idx = 8*d + w is INHERITED from the WTA\n");
W("## factor if it never changes d, and from the DN factor if it never changes\n");
W("## w.  It is COMPOSITE only if some state is moved to a state differing in\n");
W("## BOTH coordinates -- such a permutation is not a permutation of either\n");
W("## factor alone.  Counts below are over all image sets of each skeleton\n");
W("## carrying a nontrivial permutator group (see compositeness.g).\n");
W("##\n");
W("## An explicit witness for the W_to_D key claim:\n");
Mw := Monoid(gens_W_to_D);; skw := Skeleton(Mw);;
Cw := FiniteSet([5,14], 32);;
sw := Filtered(AsList(Mw), t -> OnFiniteSet(Cw, t) = Cw and 5^t = 14 and 14^t = 5);;
W("gap> sw := Filtered(AsList(M), t -> OnFiniteSet(C,t)=C and 5^t=14 and 14^t=5);;\n");
W("gap> Length(sw);\n", String(Length(sw)), "\n");
W("gap> sw[1];\n", String(sw[1]), "\n");
W("##   This element maps paper state 4 = (D:0,W:4) -> ",
  String(5^sw[1] - 1), " = (D:", String(QuoInt(5^sw[1]-1, 8)), ",W:",
  String((5^sw[1]-1) mod 8), ")\n");
W("##                   and paper state 13 = (D:1,W:5) -> ",
  String(14^sw[1] - 1), " = (D:", String(QuoInt(14^sw[1]-1, 8)), ",W:",
  String((14^sw[1]-1) mod 8), ")\n");
W("##   Both the DN and the WTA coordinate change, so the swap is composite:\n");
W("##   it is not induced by a permutation of either factor on its own.\n");

CloseStream(T);
Print("wrote gap_transcript.txt\n");
