"""
Export the audited transformation systems as a GAP-readable declaration file.

GAP transformations are one-based, so a zero-based tuple (f(0),...,f(n-1)) is
exported as (f(0)+1,...,f(n-1)+1) -- the index shift of the draft's Methods.
"""
import json
from audit import (dn3_gens, dn4_gens, wta_gens, composite_gens,
                   is_aperiodic_elt, cycles)

SYSTEMS = []

fD3, fD4, fW = dn3_gens(), dn4_gens(), wta_gens()
SYSTEMS.append(("DN3", 3, fD3, [f"D{i}" for i in range(3)]))
SYSTEMS.append(("DN4", 4, fD4, [f"D{i}" for i in range(4)]))
SYSTEMS.append(("WTA", 8, fW, ["W00", "W10", "W01", "W11"]))
for scheme in ["prod", "D_to_W", "W_to_D", "rec_sync", "rec_async_D", "rec_async_W"]:
    SYSTEMS.append((scheme, 32, composite_gens(scheme, fD4, fW),
                    [f"g{i}" for i in range(4)]))


def gap_list(t):
    return "[ " + ", ".join(str(x + 1) for x in t) + " ]"


def main():
    lines = ["# Generated by export_gap.py -- do not edit.",
             "# Transformation systems of the DN/WTA finite-state audit.",
             "# One-based GAP indexing: exported entry = zero-based image + 1.",
             ""]
    meta = {}
    for name, n, gens, gnames in SYSTEMS:
        lines.append(f"### {name}: degree {n}, {len(gens)} generators "
                     f"({', '.join(gnames)})")
        lines.append(f"deg_{name} := {n};;")
        lines.append(f"gennames_{name} := [ " +
                     ", ".join(f'"{g}"' for g in gnames) + " ];;")
        lines.append(f"genlists_{name} := [")
        for i, g in enumerate(gens):
            sep = "," if i < len(gens) - 1 else ""
            lines.append(f"  {gap_list(g)}{sep}   # {gnames[i]}")
        lines.append("];;")
        lines.append(f"gens_{name} := List(genlists_{name}, "
                     f"l -> TransformationNC(l));;")
        lines.append("")
        meta[name] = dict(degree=n, gen_names=gnames,
                          gens_zero_based=[list(g) for g in gens],
                          gens_aperiodic=[is_aperiodic_elt(g) for g in gens],
                          gen_cycles=[[list(c) for c in cycles(g) if len(c) > 1]
                                      for g in gens])

    lines.append("SYSTEMS := [")
    for i, (name, n, gens, gnames) in enumerate(SYSTEMS):
        sep = "," if i < len(SYSTEMS) - 1 else ""
        lines.append(f'  rec( name := "{name}", deg := deg_{name}, '
                     f"gens := gens_{name}, gennames := gennames_{name} ){sep}")
    lines.append("];;")
    lines.append("")

    with open("gap/systems.g", "w") as fh:
        fh.write("\n".join(lines))
    with open("gap/systems_meta.json", "w") as fh:
        json.dump(meta, fh, indent=1)
    print(f"wrote gap/systems.g with {len(SYSTEMS)} systems")
    for name, n, gens, gnames in SYSTEMS:
        print(f"  {name:>12s} deg={n:>2d} gens={len(gens)} "
              f"all_aperiodic={all(is_aperiodic_elt(g) for g in gens)}")


if __name__ == "__main__":
    main()
