#!/usr/bin/env python3
"""
gen_witness_figure.py
=====================

Emit the TikZ source for the manuscript's witness figure
(witness_figure_tikz.tex): what a composite word does, drawn as functional
graphs (finite-automaton style), with the state decoding a reader needs to
parse labels like "W:4" or "(D:1, W:5)".

Every arrow is COMPUTED from the audited generators (audit.py), not drawn by
hand: the script builds the witness transformations

    h    = f_W10 . f_W00        (WTA alone; word W00 -> W10)
    h'   = f_W01 . f_W00        (the symmetric witness; word W00 -> W01)
    t    = G1 . G0              (WTA->DN cascade; word g0 -> g1)

verifies their cycles against audit_results.json, and writes one TikZ node/edge
per state/transition. If the audit numbers ever change, rerunning this script
regenerates a correct figure.

Usage:
    PYTHONPATH=$PWD python gen_witness_figure.py [--audit audit_results.json]
Then compile witness_figure_standalone.tex and convert:
    tectonic witness_figure_standalone.tex
    pdftocairo -svg witness_figure_standalone.pdf witness_figure.svg
    pdftocairo -png -r 300 -singlefile witness_figure_standalone.pdf witness_figure
"""
from __future__ import annotations

import argparse
import json

from audit import comp, cycles, composite_gens, dn4_gens, wta_gens

WTA_MEANING = {
    0: "quiescent",
    1: "gate only",
    2: "$E_2$ wins, gate silent",
    3: "$E_2$ wins, gate engaged",
    4: "$E_1$ wins, gate silent",
    5: "$E_1$ wins, gate engaged",
    6: "both active, gate silent",
    7: "both active, gate engaged",
}


def wdec(w: int) -> tuple[int, int, int]:
    return ((w >> 2) & 1, (w >> 1) & 1, w & 1)


def build_maps(audit_json: str):
    fD4, fW = dn4_gens(), wta_gens()
    h = comp(fW[1], fW[0])       # W00 then W10
    h2 = comp(fW[2], fW[0])      # W00 then W01
    G = composite_gens("W_to_D", fD4, fW)
    t = comp(G[1], G[0])         # g0 then g1
    res = {r["label"]: r for r in json.load(open(audit_json))}
    assert list(h) == res["WTA"]["witness"], "WTA witness drifted from audit"
    assert list(t) == res["W_to_D"]["witness"], "W_to_D witness drifted from audit"
    assert [c for c in cycles(h) if len(c) > 1] == [(4, 5)]
    assert [c for c in cycles(h2) if len(c) > 1] == [(2, 3)]
    assert [c for c in cycles(t) if len(c) > 1] == [(4, 13)]
    return h, h2, t


# --------------------------------------------------------------------------
# TikZ emission
# --------------------------------------------------------------------------

HEAD = r"""% ---------------------------------------------------------------------------
% witness_figure_tikz.tex -- GENERATED by gen_witness_figure.py. Do not edit
% arrows by hand: rerun the generator (it verifies them against the audit).
% Needs in the preamble: \usepackage{tikz}
%                        \usetikzlibrary{arrows.meta,calc,bending}
% ---------------------------------------------------------------------------
\definecolor{dnblue}{HTML}{2C6FBB}
\definecolor{wtared}{HTML}{D1495B}
\definecolor{cycorange}{HTML}{E07A00}
\definecolor{midgrey}{HTML}{8A8D91}

\begin{tikzpicture}[
  font=\small,
  st/.style={circle, draw=midgrey, semithick, minimum size=5.6mm, inner sep=0.5pt,
             font=\scriptsize},
  cy/.style={circle, draw=cycorange, very thick, fill=cycorange!12,
             minimum size=5.6mm, inner sep=0.5pt, font=\scriptsize},
  tr/.style={-{Stealth[length=1.7mm]}, midgrey!85, semithick},
  cyc/.style={-{Stealth[length=2mm, bend]}, cycorange, very thick},
  lbl/.style={font=\footnotesize},
  tlb/.style={font=\scriptsize},
]
"""

TAIL = "\\end{tikzpicture}\n"


def panel_table() -> str:
    """Panel (a): the WTA state code and the composite index."""
    rows = []
    for q in range(8):
        x1, x2, y = wdec(q)
        rows.append(
            f"${q}$ & ${x1}\\,{x2}\\,{y}$ & {WTA_MEANING[q]} \\\\"
        )
    body = "\n      ".join(rows)
    return (
        "% ----- panel a: state decoding -------------------------------------\n"
        "\\node[lbl, anchor=west] at (-0.2,2.30)\n"
        "  {\\textbf{a}\\hspace{5pt}reading a state label};\n"
        "\\node[anchor=north west, font=\\scriptsize] at (-0.2,1.85) {%\n"
        "  \\renewcommand{\\arraystretch}{1.12}%\n"
        "  \\begin{tabular}{@{}c@{\\hspace{7pt}}c@{\\hspace{7pt}}l@{}}\n"
        "      $w$ & $x_1x_2\\,y$ & circuit reading \\\\[1pt] \\hline\n"
        f"      {body}\n"
        "  \\end{tabular}};\n"
        "\\node[tlb, anchor=north west, align=left] at (-0.2,-2.62)\n"
        "  {WTA state $w=4x_1+2x_2+y$; composite state $(D{:}d,\\,W{:}w)$ has index $8d+w$.};\n"
    )


def panel_wta(h, h2) -> str:
    """Panel (b): the WTA witness as a functional graph on 8 states."""
    out = ["% ----- panel b: WTA witness functional graph -----------------------"]
    out.append("\\begin{scope}[shift={(5.4,0)}]")
    out.append("\\node[lbl, anchor=west] at (-0.5,2.30) "
               "{\\textbf{b}\\hspace{5pt}WTA alone: "
               "$h=f^{W}_{10}\\circ f^{W}_{00}$ (word $W00\\;W10$)};")
    cyc = {4, 5}
    xs = 1.28
    # nodes 0..7 in a row at y=1.05
    for q in range(8):
        style = "cy" if q in cyc else "st"
        out.append(f"\\node[{style}] (b{q}) at ({q*xs:.2f},1.05) {{${q}$}};")
    # non-cycle arrows bend below the row; distance scales with hop length
    for q in range(8):
        if q in cyc:
            continue
        img = h[q]
        bend = 22 + 7 * abs(img - q)
        out.append(f"\\draw[tr] (b{q}) to[bend right={bend}] (b{img});")
    # the 2-cycle
    out.append("\\draw[cyc] (b4) to[bend left=35] (b5);")
    out.append("\\draw[cyc] (b5) to[bend left=35] (b4);")
    out.append("\\node[tlb, cycorange] at (5.75,2.02) {$4\\leftrightarrow 5$};")
    c2 = [c for c in cycles(h2) if len(c) > 1][0]
    pair2 = "$\\{" + f"{min(c2)},{max(c2)}" + "\\}$"
    out.append(
        "\\node[tlb, anchor=north west, align=left] at (-0.5,-1.05)\n"
        "  {every state falls into the pair $\\{4,5\\}$: $E_1$ has won, and $h$\\\\"
        "   toggles only the inhibitory gate ($4\\leftrightarrow5$). "
        "On the image, $h$ is the\\\\ transposition $(4\\;5)$: reversible, "
        "though neither $f^{W}_{00}$ nor $f^{W}_{10}$ is.\\\\"
        "   the symmetric word $W00\\;W01$ gives the $E_2$ cycle " + pair2 + ".};")
    out.append("\\end{scope}")
    return "\n".join(out) + "\n"


def panel_composite(t) -> str:
    """Panel (c): the composite witness on the 4x8 grid, all arrows computed."""
    out = ["% ----- panel c: composite witness on the product grid --------------"]
    out.append("\\begin{scope}[shift={(0,-5.9)}]")
    out.append("\\node[lbl, anchor=west] at (-0.2,2.05) "
               "{\\textbf{c}\\hspace{5pt}WTA$\\to$DN cascade: "
               "$t=G_{1}\\circ G_{0}$ (word $g_0\\,g_1$) on the product space};")
    xs, ys = 1.28, 0.98
    cyc = {4, 13}
    def pos(i):
        d, w = divmod(i, 8)
        return w * xs, -d * ys
    for i in range(32):
        x, y = pos(i)
        style = "cy" if i in cyc else "st"
        out.append(f"\\node[{style}] (c{i}) at ({x:.2f},{y:.2f}) {{}};")
    # row/col labels
    for d in range(4):
        out.append(f"\\node[tlb, anchor=east] at (-0.55,{-d*ys:.2f}) {{$D{{:}}{d}$}};")
    for w in range(8):
        out.append(f"\\node[tlb, anchor=north] at ({w*xs:.2f},{-3*ys-0.42:.2f}) {{$W{{:}}{w}$}};")
    # arrows
    for i in range(32):
        j = t[i]
        if i in cyc and j in cyc:
            continue  # drawn separately
        if i == j:
            out.append(f"\\draw[tr] (c{i}) to[out=55, in=125, looseness=6] (c{i});")
        else:
            di, wi = divmod(i, 8); dj, wj = divmod(j, 8)
            bend = 12 + 3 * (abs(wi - wj) + abs(di - dj))
            side = "left" if (wi > wj or (wi == wj and di > dj)) else "right"
            out.append(f"\\draw[tr] (c{i}) to[bend {side}={bend}] (c{j});")
    out.append("\\draw[cyc] (c4) to[bend left=30] (c13);")
    out.append("\\draw[cyc] (c13) to[bend left=30] (c4);")
    out.append("\\node[tlb, cycorange, anchor=west] at "
               f"({5*xs+0.72:.2f},{0.62:.2f}) "
               "{$(D{:}0,W{:}4)\\leftrightarrow(D{:}1,W{:}5)$};")
    out.append("\\end{scope}")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--audit", default="audit_results.json")
    ap.add_argument("--out", default="witness_figure_tikz.tex")
    args = ap.parse_args()
    h, h2, t = build_maps(args.audit)
    src = HEAD + panel_table() + panel_wta(h, h2) + panel_composite(t) + TAIL
    with open(args.out, "w") as fh:
        fh.write(src)
    print(f"wrote {args.out}: verified cycles "
          f"WTA {sorted(c for c in cycles(h) if len(c)>1)}, "
          f"composite {sorted(c for c in cycles(t) if len(c)>1)}")


if __name__ == "__main__":
    main()
